<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>SecAudit.Modules.RemoteAccess</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\SecAudit.Plugins.Abstractions\SecAudit.Plugins.Abstractions.csproj" />
    <ProjectReference Include="..\SecAudit.Core\SecAudit.Core.csproj" />
    <ProjectReference Include="..\SecAudit.Infrastructure\SecAudit.Infrastructure.csproj" />
    <ProjectReference Include="..\SecAudit.Modules.SystemInfo\SecAudit.Modules.SystemInfo.csproj" />
  </ItemGroup>
</Project>
